version: "3"
services:
  db:
    image: postgres
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=defipools
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - pg-net
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
networks:
  pg-net:
  redis-net:
volumes:
  db-data:
  redis-data:
