GET http://localhost:5000/api/status HTTP/1.1

###

GET http://localhost:5000/api/blocks HTTP/1.1

### Snapshot By Block
#GET http://localhost:5000/api/blocks/14352639 HTTP/1.1


### Snapshot By Block: getSnapshoDataByBlockNumber
GET http://localhost:5000/api/snapshot/14461107 HTTP/1.1


### Snapshot By Account & BlockNumber
GET http://localhost:5000/api/snapshot/14461107/0xca54c3123c855bceceb0db69B034E45530020F26 HTTP/1.1


### Row !!! Snapshot By Account & BlockNumber
GET http://localhost:5000/api/snapshot/row/14352639/0xc43f964622440356da60bee2d543a4023a8bcff8 HTTP/1.1


### Scanner 
GET http://localhost:5000/api/scanner HTTP/1.1